services:
### push-notifications ##################################
  push-notifications:
    image: node:12-slim
    # On Linux, these lines ensure file ownership is set to your host user/group
    user: "${MW_DOCKER_UID}:${MW_DOCKER_GID}"
    volumes:
      - ./:/srv/push-notifications
      - ./certs:/etc/mediawiki-services-push-notifications/certs
    working_dir: /srv/push-notifications
    tty: true
    network_mode: host
