pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: built
        build: npm-run
      - name: test
        run:
          image: '${built.imageID}'
          arguments: [test]
      - name: codehealth_built
        build: codehealth
      - name: coverage
        run:
          image: '${codehealth_built.imageID}'
          env:
            SONAR_BRANCH_TARGET: ${ZUUL_BRANCH}
            SONAR_BRANCH_NAME: '${ZUUL_CHANGE}-${ZUUL_PATCHSET}'
          credentials:
            - id: SONAR_API_KEY
              name: SONAR_API_KEY
  publish:
    blubberfile: blubber.yaml
    stages:
      - name: codehealth_built
        build: codehealth
      - name: coverage
        run:
          image: '${codehealth_built.imageID}'
          env:
            SONAR_BRANCH_NAME: ${ZUUL_BRANCH}
          credentials:
            - id: SONAR_API_KEY
              name: SONAR_API_KEY
      - name: publish
        build: production
        publish:
          image: true
